#!/usr/bin/env bash

THIS_DIR="$(dirname $(readlink -f $0))"

. /etc/os-release

create_dir_structure() {
  echo "Creating base directory structure..."
  mkdir -p $HOME/.config/
  mkdir -p ~/.config/systemd/user
  mkdir -p ~/.local/bin
  mkdir -p ~/.unison
  mkdir -p ~/.local/share/remmina
}

create_dir_structure

install_git_config() {
  echo "Installing git config..."
  git config --global core.excludesfile $HOME/dotfiles/git/.gitignore
}

uninstall_git_config() {
  echo "Installing git config..."
  git config --global --unset core.excludesfile
}

install_desktop_files() {
  echo "Installing desktop files..."
  stow desktop_files -d "$THIS_DIR/stow" -t ~
}

uninstall_desktop_files() {
  echo "Uninstalling desktop files..."
  stow -D desktop_files -d "$THIS_DIR/stow" -t ~
}

install_neovim() {
  echo 'Installing neovim'
  curl -fLo $HOME/.local/bin/nvim --create-dirs \
    https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.appimage
  # https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
  chmod +x $HOME/.local/bin/nvim
}

uninstall_neovim() {
  echo 'Uninstalling neovim'
  rm -f $HOME/.local/bin/nvim
}

install_bashrc() {
  echo 'Installing bashrc'
  # Include my bashrc in the main one if not already included
  INCLUDE_COMMAND="\nif [ -f $THIS_DIR/bash/bashrc ]; then\n  . $THIS_DIR/files/bashrc\nfi\n"
  PATTERN="if [ -f $THIS_DIR/files/bashrc ]; then"
  grep -xqF -- "$PATTERN" $HOME/.bashrc || printf "$INCLUDE_COMMAND" >>$HOME/.bashrc
}

uninstall_bashrc() {
  echo 'Uninstalling bashrc'
  # Remove my bashrc from the main one if it exists
  grep -xqF -- "$PATTERN" $HOME/.bashrc
  if [ $? -eq 0 ]; then
    sed -i "/$PATTERN/,+3d" $HOME/.bashrc
  fi
}

install_vim() {
  echo 'Installing VIM'
  read -p "Install full lazyVim(1) or basic neovim(2)?: " choice

  if [ "$choice" = "1" ]; then
    echo 'Installing LazyVIM'
    stow lazyvim -d "$THIS_DIR/stow" -t ~
  elif [ "$choice" = "2" ]; then
    echo 'Installing basic neovim'
    stow neovim -d "$THIS_DIR/stow" -t ~
  fi
}

uninstall_vim() {
  echo 'Uninstalling VIM'
  stow -D lazyvim -d "$THIS_DIR/stow" -t ~
  stow -D neovim -d "$THIS_DIR/stow" -t ~
}

install_unison() {
  read -p "Setup unison? (y/n): " choice
  if [ "$choice" = "y" ]; then
    echo 'Installing unison'
    $INSTALL_CMD unison
    stow unison -d "$THIS_DIR/stow" -t ~
  fi
}

uninstall_unison() {
  echo 'Uninstalling unison'
  stow -D unison -d "$THIS_DIR/stow" -t ~
}

if [ "$ID" = "debian" ]; then
  sudo apt update
  INSTALL_CMD="sudo apt install -y"
elif uname -a | grep -i "arch" >/dev/null; then
  sudo pacman -Syy --noconfirm
  INSTALL_CMD="sudo pacman -S --noconfirm"
fi

$INSTALL_CMD curl git fuse libfuse2 xclip git rsync stow

# GIT
if [ "$1" = "--uninstall" ]; then
  uninstall_git_config
else
  install_git_config
fi
# GIT

# Desktop files
if [ "$1" = "--uninstall" ]; then
  uninstall_desktop_files
else
  install_desktop_files
fi
# Desktop files

### NEOVIM
if [ "$1" = "--uninstall" ]; then
  uninstall_neovim
else
  install_neovim
fi
### NEOVIM

### BASHRC
if [ "$1" = "--uninstall" ]; then
  uninstall_bashrc
else
  install_bashrc
fi
### BASHRC


### VIM
if [ "$1" = "--uninstall" ]; then
  uninstall_vim
else
  install_vim
fi
### VIM

### SCRIPTS
echo 'Installing scripts'
if [ "$1" = "--uninstall" ]; then
  stow -D scripts -d "$THIS_DIR/stow" -t ~
  popd
else
  stow scripts -d "$THIS_DIR/stow" -t ~
fi
### SCRIPTS

### UNISON
if [ "$1" = "--uninstall" ]; then
  uninstall_unison
else
  install_unison
fi

### TMUX
if [ "$1" = "--uninstall" ]; then
  stow -D tmux -d "$THIS_DIR/stow" -t ~
else
  stow tmux -d "$THIS_DIR/stow" -t ~
fi
### TMUX
