#!/usr/bin/env bash

THIS_DIR="$(dirname $(readlink -f $0))"

sudo apt update
sudo apt install -y curl git fuse libfuse2 xclip git rsync stow

exec "$THIS_DIR/../common/common"

echo 'Installing bashrc'
# Include my bashrc in the main one if not already included
INCLUDE_COMMAND="\nif [ -f $THIS_DIR/files/bashrc ]; then\n  . $THIS_DIR/files/bashrc\nfi\n"
PATTERN="if [ -f $THIS_DIR/files/bashrc ]; then"
grep -xqF -- "$PATTERN" $HOME/.bashrc || printf "$INCLUDE_COMMAND" >>$HOME/.bashrc

